### ISSUE TITLE
Javascript error in ckeditor.js - Uncaught TypeError: a is undefined

### ISSUE THREAD

**Issue by medarob** [nitsan-technologies/ns_guestbook#6]
Hi,

I included the Typoscript of the guestbook extension on my root page (as described in the documentation). (The guestbook is on a subpage.)

When I open the root page (where there is no guestbook) I get the following error in the console:

![grafik](https://user-images.githubusercontent.com/33951787/88021048-14229900-cb2d-11ea-9dee-65441e4f92ce.png)

I'm using 2.1 of the guestbook extension and TYPO3 9.5.19.

**Comment by medarob** [comment]
I get some more errors on the live system.

![grafik](https://user-images.githubusercontent.com/33951787/88053664-7646c280-cb5c-11ea-8975-e797baa65085.png)

Not sure why they appear but the ckeditor is not loading and I have no textarea input field visible in the frontend.

If I disable the plugin on the page the error in my post above is shown.

**Comment by JanStorm** [comment]
We ran into a similar issue: `Uncaught TypeError: Cannot read properties of undefined (reading 'getEditor')`, which is also caused by `a` being undefined on pages where the JS is loaded but no editor-textarea exists. Our solution for now is to override the `Resources/Public/js/custom.js`, adding a `if (document.getElementById('editor1'))` before the initialization call. This prevents the js being executed on pages where no editor is loaded and therefore `a` being undefined.

TYPO3 8.7, ns_guestbook v3.0.2

**Comment by JanStorm** [comment]
Just found this approach as a part of this existing merge request: https://github.com/nitsan-technologies/ns_guestbook/pull/8

**Comment by nitsan-technologies** [comment]
Hello there!

FYI, We have resolved this issue and now you may download/update the latest version of the extension.
Thanks for pointing out the issue.

Thanks!
Team NITSAN
